name: human-age-prediction
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - pillow
  - jupyter
  - jupyterlab
  - pip
  - pip:
      - tensorflow==2.18.0
      - opencv-python
      - tqdm
